### ISSUE TITLE
errors with tstl

### ISSUE THREAD

**Issue by zoeleu** [hazzard993/love-typescript-template#11]
```
PS C:\Users\Matteo\Documents\bombix-love> yarn build
yarn run v1.22.19
$ yarn build:tstl && yarn build:copy
$ tstl -p tsconfig.json
C:\Users\Matteo\Documents\bombix-love\node_modules\typescript\lib\typescript.js:98681
                throw e;
                ^

TypeError: Cannot read properties of undefined (reading 'updateCallExpression')
    at visit (C:\Users\Matteo\Documents\bombix-love\node_modules\typescript-to-lua\dist\transpilation\transformers.js:59:31)
    at visitNode (C:\Users\Matteo\Documents\bombix-love\node_modules\typescript\lib\typescript.js:73037:23)
    at Object.visitEachChild (C:\Users\Matteo\Documents\bombix-love\node_modules\typescript\lib\typescript.js:73350:224)
    at visit (C:\Users\Matteo\Documents\bombix-love\node_modules\typescript-to-lua\dist\transpilation\transformers.js:67:19)
    at visitNodes (C:\Users\Matteo\Documents\bombix-love\node_modules\typescript\lib\typescript.js:73088:48)
    at Object.visitEachChild (C:\Users\Matteo\Documents\bombix-love\node_modules\typescript\lib\typescript.js:73352:63)
    at visit (C:\Users\Matteo\Documents\bombix-love\node_modules\typescript-to-lua\dist\transpilation\transformers.js:67:19)
    at visitNode (C:\Users\Matteo\Documents\bombix-love\node_modules\typescript\lib\typescript.js:73037:23)
    at Object.visitEachChild (C:\Users\Matteo\Documents\bombix-love\node_modules\typescript\lib\typescript.js:73318:111)
    at visit (C:\Users\Matteo\Documents\bombix-love\node_modules\typescript-to-lua\dist\transpilation\transformers.js:67:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by zoeleu** [comment]
found the issue, install latest version of ``typescript-to-lua`` and ``typescript@4.6.2``

**Comment by hazzard993** [comment]
Thanks for the report! Updated those dependencies now
